### ISSUE TITLE
Do you thing support netcoreapp2.1

### ISSUE THREAD

**Issue by sargin48** [Rinsen/OneWire#11]
Do you thing support netcoreapp2.1 project type

**Comment by Rinsen** [comment]
My plan is to try to get some things done in this project during the winter. So if it's possible without any issues this might be a net standard project. 

But I don't really know how it will work with the i2c parts that are windows only, It might work just fine.

**Comment by Rinsen** [comment]
As it seems this is not possible right now, or I can't figure out how to do it at least. 

File a new issue is this is relevant and possible in the future.

**Comment by Rinsen** [comment]
@sargin48 

Hi! This is now possible to do, I have a beta release "3.0-beta" out on Nuget now that is built on Net Standard 2.0.
