### ISSUE TITLE
Add Support For LightningProvider

### ISSUE THREAD

**Issue by spacepost** [Rinsen/OneWire#12]
Currently, this project only works with the standard (inbox) drivers. A minor tweak is required to add support for the lightning drivers.

**Comment by Rinsen** [comment]
What is the biggest advantages with using Lightning? 

I have not used that at all.

**Comment by spacepost** [comment]
Gpio performance is the primary benefit. I use the OneWire code in an aquarium controller to read temperature probes. The controller also controls the lighting and requires lightning drivers for PWM. I will submit a pull request for you with the adjustment. The change to add a constructor that accepts an i2c device would probably also work. I haven't tried it out yet.

**Comment by Rinsen** [comment]
In the latest release it's now possible to locate and send in whatever i2c device you want and handle the lifetime out side of my framework.

I have no plans currently to add in lightning drivers.

**Comment by Rinsen** [comment]
@spacepost 

The latest beta version is now build on top of https://github.com/dotnet/iot i2c library instead of the previous. I am unsure what they use below the surface but It's at least not built on the same library as previously.
