### ISSUE TITLE
Announcement: New version released

### ISSUE THREAD

**Issue by Rinsen** [Rinsen/OneWire#13]
I have released a new version with a lot of new features but also some breaking changes. 

See the sample app and documentation for more details.

**Comment by bmasephol** [comment]
Thanks for continuing to work on this project, I'll pull in the latest changes and update my project with it.

**Comment by Rinsen** [comment]
It's starting to get quite matureure and is a really fun project to work with and awesome for home automation so I'm planning to continue to work with this as long as it's relevant!
