### ISSUE TITLE
Support DS2482-800

### ISSUE THREAD

**Issue by treetopvt** [Rinsen/OneWire#4]
What is the level of effort to support the 800 version of the chip?  I love the idea of a full C# version of DS1820B temperature monitors, but I do not want to be limited by 4 sensors.

**Comment by Rinsen** [comment]
I will do some investigation and see how much is needed, in the best of world it is simple. 

I will get back in some day's, but I have a lot to do during the holidays so it can take some time.

**Comment by Rinsen** [comment]
I will have this implement in a week or two as I think it should be pretty easy to do. I will link a pull request here when I have started and it would be great if you could try it out.
I have ordered a chip from ebay but it will take some time to before I have it and have built a test setup for it.

I would also like to make it possible to run multiple DS2482 chips on the same i2c bus so you could scale it to even more sensors. But that will come later. :-)

**Comment by treetopvt** [comment]
That is great news, thank you for investigating.  I have an 800 and 4 100's
on order myself and I will be happy to test as necessary.

**Comment by Rinsen** [comment]
@treetopvt 
Things is moving a bit slow, lack of time and the first idea I had got a bit messy so I will try to create channels that each OneWireDevice is using to communicating with the DS2482 controller regardless of type of controller. 

Some of the work is located in this PR
https://github.com/Rinsen/OneWire/pull/6

**Comment by treetopvt** [comment]
Thank you I will take a look.  I have the chip and I am ready to test when
you are.

**Comment by Rinsen** [comment]
I have added a new commit that could make it work, but I have not tested it in any way except that it builds so don´t expect to much :)  

I will try to test runt it with my DS2482-100 as soon as possible.

**Comment by Rinsen** [comment]
I have not received any DS2482-800 device so I have not done any tests on this yet. 

I will get back as soon as possible.

**Comment by Rinsen** [comment]
After a very very long time I have now released a new version with support for this!
