### ISSUE TITLE
Add I2cDevice to OneWireDeviceHandler ctor

### ISSUE THREAD

**Issue by reesesm2000** [Rinsen/OneWire#7]
Firstly, thanks for a great project. Just started using it but going well so far.

I need a OneWireDeviceHandler ctor with a I2cDevice instead of the AD0/AD1 parameters. Long story but basically I am auto discovering what is connected to my I2C bus and instead of creating a device to detect the DS2482 and then disposing of it and then letting OneWireDeviceHandler create it again, adding a new ctor is more efficient. Below is what I added to line 60 of OneWireDeviceHandler.cs for your consideration in one of the next builds.

        /// <summary>
        /// One wire device handler via DS2482-100
        /// </summary>
        /// <param name="i2cDevice">Opened I2cDevice</param>
        /// <exception cref="Rinsen.IoT.OneWire.DS2482100DeviceNotFoundException">Thrown if no DS2482-100 device is detected</exception>
        public OneWireDeviceHandler(Windows.Devices.I2c.I2cDevice i2cDevice)
        {
            _ds2482_100 = new DS2482_100(i2cDevice);

            try
            {
                _ds2482_100.OneWireReset();
            }
            catch (Exception e)
            {
                throw new DS2482100DeviceNotFoundException("No DS2482-100 detected, check that AD0 and AD1 is correct in ctor and that the physical connection to the DS2482-100 one wire bridge is correct.", e);
            }

            _oneWireDeviceTypes = new Dictionary<byte, Type>();

            AddDeviceType<DS18S20>(0x10);
            AddDeviceType<DS18B20>(0x28);
        }

**Comment by Rinsen** [comment]
I am working on a new version and will try to include this in a good and reliable way, I have some hardware issues that have stalled the development on the new version right now but will continue as soon as that is resolved...

**Comment by reesesm2000** [comment]
Ok great. Let me know if you need a hand with anything. I am building a quite extensive control solution that uses One Wire (amongst a few other protocols too). Waiting for my DS2408 and DS2413 devices to arrive and will send you the updated Device files once I build it out.

**Comment by Rinsen** [comment]
I have added the possibility to do this now in a pull request that you can find here. 
https://github.com/Rinsen/OneWire/pull/6

This code is not very well tested since I have had issues with my hardware so there can be some unexpected behaviors. 

But if you are interested and have time please test it and give feedback! When I find time I will try to fix my hardware issues and test this more.

**Comment by Rinsen** [comment]
This is now in place in the 2.0 release
